// CLASSROOMS ACTIONS
export const LOAD_CLASSROOMS = "LOAD_CLASSROOMS";
export const NEW_CLASSROOM = "NEW_CLASSROOM";
export const GET_CLASSROOM_SELECTED = "GET_CLASSROOM_SELECTED";
export const DELETE_CLASSROOM = "DELETE_CLASSROOM";
export const EDIT_CLASSROOM = "EDIT_CLASSROOM";

// STUDENTS ACTIONS
export const LOAD_STUDENTS_CLASSROOM = "LOAD_STUDENTS_CLASSROOM";
export const LOAD_TOTAL_STUDENTS = "LOAD_TOTAL_STUDENTS";
export const NEW_STUDENT = "NEW_STUDENT";
export const DELETE_STUDENT = "DELETE_STUDENT";
export const EDIT_STUDENT = "EDIT_STUDENT";

// UI ACTIONS
export const OPEN_MODAL_CLASS = "OPEN_MODAL_CLASS";
export const CLOSE_MODAL_CLASS = "CLOSE_MODAL_CLASS";
export const OPEN_MODAL_STUDENTS = "OPEN_MODAL_STUDENTS";
export const CLOSE_MODAL_STUDENTS = "CLOSE_MODAL_STUDENTS";
export const OPEN_MODAL_EDIT_STUDENTS = "OPEN_MODAL_EDIT_STUDENTS";
export const CLOSE_MODAL_EDIT_STUDENTS = "CLOSE_MODAL_EDIT_STUDENTS";
export const OPEN_MODAL_EDIT_CLASSROOM = "OPEN_MODAL_EDIT_CLASSROOM";
export const CLOSE_MODAL_EDIT_CLASSROOM = "CLOSE_MODAL_EDIT_CLASSROOM";
export const TOGGLE_VIEW_TOTALS = "TOGGLE_VIEW_TOTALS";
